# Generated by Django 4.1 on 2023-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=50, unique=True, verbose_name='Короткое название')),
                ('dir_path', models.CharField(max_length=250, unique=True, verbose_name='Относительный путь')),
                ('class_nums', models.IntegerField(verbose_name='Количество классов')),
                ('size', models.IntegerField(verbose_name='Количество образцов')),
            ],
            options={
                'verbose_name': 'Датасет',
                'verbose_name_plural': '01 Датасеты',
                'ordering': ['-shortName'],
            },
        ),
        migrations.CreateModel(
            name='INS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=50, unique=True, verbose_name='Короткое название')),
                ('dir_path', models.CharField(max_length=250, unique=True, verbose_name='Относительный путь')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': '02 Модели',
                'ordering': ['-shortName'],
            },
        ),
    ]
