# Generated by Django 4.1 on 2023-06-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ins',
            old_name='dir_path',
            new_name='dir_name',
        ),
    ]
