# Generated by Django 4.1 on 2023-06-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_dataset_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ins',
            name='arguments',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ins',
            name='build_shape',
            field=models.BooleanField(default=1, verbose_name='Build need'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ins',
            name='comments',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ins',
            name='input_size_ch',
            field=models.IntegerField(default=1, verbose_name='Channels num'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ins',
            name='input_size_x',
            field=models.IntegerField(default=1, verbose_name='Size X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ins',
            name='input_size_y',
            field=models.IntegerField(default=1, verbose_name='Size Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ins',
            name='max',
            field=models.FloatField(default=1, verbose_name='Max values input'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ins',
            name='min',
            field=models.FloatField(default=1, verbose_name='Min values input'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ins',
            name='type',
            field=models.IntegerField(default=1, verbose_name='Вектор признаков (0), классификатор(1)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ins',
            name='dir_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='ins',
            name='shortName',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя модели'),
        ),
    ]
