# Generated by Django 4.1 on 2023-06-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_ins_arguments_ins_build_shape_ins_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ins',
            name='max',
            field=models.IntegerField(verbose_name='Max values input'),
        ),
        migrations.AlterField(
            model_name='ins',
            name='min',
            field=models.IntegerField(verbose_name='Min values input'),
        ),
    ]
