# Generated by Django 4.1 on 2023-06-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_ins_arguments_ins_batch_norm_momentum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ins',
            name='build_shape',
        ),
    ]
