# Generated by Django 4.1 on 2023-06-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_ins_build_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='ins',
            name='dir_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
