# Generated by Django 4.1 on 2023-06-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_ins_dir_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ins',
            name='batch_norm_momentum',
            field=models.FloatField(null=True),
        ),
    ]
