# Generated by Django 4.1 on 2023-06-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_rename_experiment_attack_experimentattack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentattack',
            options={'ordering': ['-shortName'], 'verbose_name': 'Эксперимент_атака', 'verbose_name_plural': '04 Эксперимент_атаки'},
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='type',
        ),
    ]
