# Generated by Django 4.1 on 2023-06-19 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_experimentdefense_eps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentresult',
            options={'verbose_name': 'Результат эксперимента', 'verbose_name_plural': '07 Результаты экспериментов'},
        ),
        migrations.CreateModel(
            name='TrainModelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.JSONField(blank=True, null=True, verbose_name='param')),
                ('result_json', models.JSONField(verbose_name='result')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.ins')),
            ],
            options={
                'verbose_name': 'Итог тренировки модели',
                'verbose_name_plural': '06 Тренированные модели',
            },
        ),
    ]
